In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:\AI-Connected-Vehicle-Analytics\data\historical\connected_vehicle_telemetry.csv")

Dataset Shape: (50000, 42)

Columns:
['vehicle_id', 'brand', 'vehicle_year', 'timestamp', 'odometer_km', 'engine_hours', 'vehicle_speed_kph', 'engine_temp_c', 'engine_rpm', 'oil_pressure_psi', 'coolant_temp_c', 'fuel_level_percent', 'fuel_consumption_lph', 'engine_load_percent', 'throttle_position_percent', 'air_flow_rate_gps', 'exhaust_gas_temp_c', 'engine_vibration', 'brake_pad_wear_mm', 'brake_fluid_level', 'brake_temp_c', 'abs_fault_indicator', 'brake_pedal_position', 'wheel_speed_fl_kph', 'wheel_speed_fr_kph', 'wheel_speed_rl_kph', 'wheel_speed_rr_kph', 'battery_voltage_v', 'battery_current_a', 'battery_temp_c', 'alternator_output_v', 'battery_charge_percent', 'battery_health_percent', 'ambient_temp_c', 'humidity_percent', 'gps_latitude', 'gps_longitude', 'engine_failure_imminent', 'brake_issue_imminent', 'battery_issue_imminent', 'failure_date', 'failure_type']

First 5 Records:

,vehicle_id,brand,vehicle_year,timestamp,odometer_km,engine_hours,vehicle_speed_kph,engine_temp_c,engine_rpm,oil_pressure_psi,...,battery_health_percent,ambient_temp_c,humidity_percent,gps_latitude,gps_longitude,engine_failure_imminent,brake_issue_imminent,battery_issue_imminent,failure_date,failure_type
0,VEH0005,BMW,2021,2025-12-14 11:40:00,96065.16,1886.89,90.75,108.34,3698.46,57.05,...,94.60,33.55,39.52,10.310915,80.114368,0,0,0,2050-01-01 00:00:00,No Failure
1,VEH0064,Tata,2021,2025-06-18 09:03:00,92417.05,2216.19,61.83,100.82,2845.62,58.07,...,100.00,22.48,69.05,15.461133,79.417808,0,0,0,2050-01-01 00:00:00,No Failure
2,VEH0179,Honda,2017,2025-10-27 13:54:00,151027.57,3237.27,71.16,84.91,3033.65,50.60,...,83.34,20.49,23.88,19.944140,81.286649,0,0,0,2050-01-01 00:00:00,No Failure
3,VEH0188,Toyota,2024,2025-08-21 18:35:00,39957.50,585.93,109.16,108.41,4081.99,56.52,...,98.81,22.17,76.03,24.034787,87.145007,0,0,0,2050-01-01 00:00:00,No Failure
4,VEH0210,Mercedes,2018,2025-08-22 09:15:00,151016.74,3315.73,51.11,103.20,3083.58,54.53,...,89.32,26.58,40.56,8.726361,75.954270,0,0,0,2050-01-01 00:00:00,No Failure

In [2]:
print("Dataset Shape:", df.shape)

Dataset Shape: (50000, 42)

In [3]:
print("\nColumns:")
print(df.columns.tolist())

Columns:
['vehicle_id', 'brand', 'vehicle_year', 'timestamp', 'odometer_km', 'engine_hours', 'vehicle_speed_kph', 'engine_temp_c', 'engine_rpm', 'oil_pressure_psi', 'coolant_temp_c', 'fuel_level_percent', 'fuel_consumption_lph', 'engine_load_percent', 'throttle_position_percent', 'air_flow_rate_gps', 'exhaust_gas_temp_c', 'engine_vibration', 'brake_pad_wear_mm', 'brake_fluid_level', 'brake_temp_c', 'abs_fault_indicator', 'brake_pedal_position', 'wheel_speed_fl_kph', 'wheel_speed_fr_kph', 'wheel_speed_rl_kph', 'wheel_speed_rr_kph', 'battery_voltage_v', 'battery_current_a', 'battery_temp_c', 'alternator_output_v', 'battery_charge_percent', 'battery_health_percent', 'ambient_temp_c', 'humidity_percent', 'gps_latitude', 'gps_longitude', 'engine_failure_imminent', 'brake_issue_imminent', 'battery_issue_imminent', 'failure_date', 'failure_type']

In [4]:
print("\nFirst 5 Records:")
display(df.head())

First 5 Records:

,vehicle_id,brand,vehicle_year,timestamp,odometer_km,engine_hours,vehicle_speed_kph,engine_temp_c,engine_rpm,oil_pressure_psi,...,battery_health_percent,ambient_temp_c,humidity_percent,gps_latitude,gps_longitude,engine_failure_imminent,brake_issue_imminent,battery_issue_imminent,failure_date,failure_type
0,VEH0005,BMW,2021,2025-12-14 11:40:00,96065.16,1886.89,90.75,108.34,3698.46,57.05,...,94.60,33.55,39.52,10.310915,80.114368,0,0,0,2050-01-01 00:00:00,No Failure
1,VEH0064,Tata,2021,2025-06-18 09:03:00,92417.05,2216.19,61.83,100.82,2845.62,58.07,...,100.00,22.48,69.05,15.461133,79.417808,0,0,0,2050-01-01 00:00:00,No Failure
2,VEH0179,Honda,2017,2025-10-27 13:54:00,151027.57,3237.27,71.16,84.91,3033.65,50.60,...,83.34,20.49,23.88,19.944140,81.286649,0,0,0,2050-01-01 00:00:00,No Failure
3,VEH0188,Toyota,2024,2025-08-21 18:35:00,39957.50,585.93,109.16,108.41,4081.99,56.52,...,98.81,22.17,76.03,24.034787,87.145007,0,0,0,2050-01-01 00:00:00,No Failure
4,VEH0210,Mercedes,2018,2025-08-22 09:15:00,151016.74,3315.73,51.11,103.20,3083.58,54.53,...,89.32,26.58,40.56,8.726361,75.954270,0,0,0,2050-01-01 00:00:00,No Failure

In [5]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
vehicle_id                   0
brand                        0
vehicle_year                 0
timestamp                    0
odometer_km                  0
engine_hours                 0
vehicle_speed_kph            0
engine_temp_c                0
engine_rpm                   0
oil_pressure_psi             0
coolant_temp_c               0
fuel_level_percent           0
fuel_consumption_lph         0
engine_load_percent          0
throttle_position_percent    0
air_flow_rate_gps            0
exhaust_gas_temp_c           0
engine_vibration             0
brake_pad_wear_mm            0
brake_fluid_level            0
brake_temp_c                 0
abs_fault_indicator          0
brake_pedal_position         0
wheel_speed_fl_kph           0
wheel_speed_fr_kph           0
wheel_speed_rl_kph           0
wheel_speed_rr_kph           0
battery_voltage_v            0
battery_current_a            0
battery_temp_c               0
alternator_output_v          0
battery_charge_percent       0
battery_health_percent       0
ambient_temp_c               0
humidity_percent             0
gps_latitude                 0
gps_longitude                0
engine_failure_imminent      0
brake_issue_imminent         0
battery_issue_imminent       0
failure_date                 0
failure_type                 0
dtype: int64

In [6]:
print("\nDuplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
0

In [7]:
print("\nData Types:")
print(df.dtypes)

Data Types:
vehicle_id                       str
brand                            str
vehicle_year                   int64
timestamp                        str
odometer_km                  float64
engine_hours                 float64
vehicle_speed_kph            float64
engine_temp_c                float64
engine_rpm                   float64
oil_pressure_psi             float64
coolant_temp_c               float64
fuel_level_percent           float64
fuel_consumption_lph         float64
engine_load_percent          float64
throttle_position_percent    float64
air_flow_rate_gps            float64
exhaust_gas_temp_c           float64
engine_vibration             float64
brake_pad_wear_mm            float64
brake_fluid_level            float64
brake_temp_c                 float64
abs_fault_indicator            int64
brake_pedal_position         float64
wheel_speed_fl_kph           float64
wheel_speed_fr_kph           float64
wheel_speed_rl_kph           float64
wheel_speed_rr_kph           float64
battery_voltage_v            float64
battery_current_a            float64
battery_temp_c               float64
alternator_output_v          float64
battery_charge_percent       float64
battery_health_percent       float64
ambient_temp_c               float64
humidity_percent             float64
gps_latitude                 float64
gps_longitude                float64
engine_failure_imminent        int64
brake_issue_imminent           int64
battery_issue_imminent         int64
failure_date                     str
failure_type                     str
dtype: object

Checking failure information

In [ ]:
# 0--> for NO imminent engine failure 
#  1 --> Engine failure is imminent


print("Engine failures:")
print(df["engine_failure_imminent"].value_counts())

print("\nBrake failures:")
print(df["brake_issue_imminent"].value_counts())

print("\nBattery failures:")
print(df["battery_issue_imminent"].value_counts())

print("\nFailure types:")
print(df["failure_type"].value_counts())

Engine failures:
engine_failure_imminent
0    47000
1     3000
Name: count, dtype: int64

Brake failures:
brake_issue_imminent
0    47000
1     3000
Name: count, dtype: int64

Battery failures:
battery_issue_imminent
0    47000
1     3000
Name: count, dtype: int64

Failure types:
failure_type
No Failure    41890
Brake          2438
Engine         2425
Battery        2400
Multiple        847
Name: count, dtype: int64

In [ ]:
df["failure"] = (
    (df["engine_failure_imminent"] == 1) |
    (df["brake_issue_imminent"] == 1) |
    (df["battery_issue_imminent"] == 1)
).astype(int)

print(df["failure"].value_counts())

# failure = 0 → Normal
#  failure = 1 → Failure risk

failure
0    41890
1     8110
Name: count, dtype: int64